import { preview } from 'vite';
import { chromium } from 'playwright';
import fs from 'fs';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { findChromiumExecutable } = require('../config/paths');

const EXECUTABLE = findChromiumExecutable();
const EVIDENCE_DIR = 'runtime-evidence/deep-platform';
fs.mkdirSync(EVIDENCE_DIR, { recursive: true });
const results = { suite: 'UX_EXPERIENCE_REAL_BROWSER_V1', checks: [] };
let previewServer = null, browser = null, failed = false;
const LEGACY_VERDICT_RE = /يوصى بالشراء|لا يوصى بالشراء/;
function record(name, passed, detail=null){results.checks.push({name,status:passed?'PASS':'FAIL',detail});if(!passed)failed=true;}
async function loadReferenceDeal(page,nameRe){await page.getByTitle('الصفقات المحفوظة').click();await page.waitForTimeout(200);await page.getByRole('button',{name:nameRe}).first().click();await page.waitForTimeout(300);}
async function enterExplicitBuildingExitCap(page,value='8.5'){const b=page.getByRole('button',{name:/افتراضات التقييم والاستثمار/}).first();const s=b.locator('xpath=ancestor::div[contains(@class,"rounded-2xl") and contains(@class,"overflow-hidden")][1]');const body=s.locator('.rf-accordion-body').first();if(!((await body.getAttribute('class'))||'').split(/\s+/).includes('open')){await b.click();await page.waitForTimeout(200);}const x=page.getByText('معدل رسملة الخروج',{exact:true}).locator('xpath=ancestor::label[1]').locator('input').first();await x.fill(value);await x.blur();await page.waitForTimeout(250);return x;}
async function viewportAudit(page,name,width,height){await page.setViewportSize({width,height});await page.waitForTimeout(150);const a=await page.evaluate(()=>{const d=document.documentElement;const v=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.visibility!=='hidden'&&s.display!=='none'&&r.width>0&&r.height>0};const i=[...document.querySelectorAll('button,a,input,select,textarea,[role="button"],[tabindex]')].filter(v);const tiny=i.filter(e=>{const r=e.getBoundingClientRect();return !e.matches('input[type="hidden"]')&&(r.width<24||r.height<24)}).map(e=>({tag:e.tagName,text:(e.innerText||e.getAttribute('aria-label')||'').trim().slice(0,60),w:Math.round(e.getBoundingClientRect().width),h:Math.round(e.getBoundingClientRect().height)}));const text=[...document.querySelectorAll('body *')].filter(v).filter(e=>{const t=(e.textContent||'').trim();return t&&e.children.length===0&&parseFloat(getComputedStyle(e).fontSize)<10}).slice(0,20).map(e=>({text:e.textContent.trim().slice(0,60),fontSize:getComputedStyle(e).fontSize}));return{scrollWidth:d.scrollWidth,clientWidth:d.clientWidth,interactiveCount:i.length,tinyTargets:tiny.slice(0,20),tinyText:text}});record(`${name}_NO_HORIZONTAL_OVERFLOW`,a.scrollWidth<=a.clientWidth+5,a);record(`${name}_TOUCH_TARGETS_24PX`,a.tinyTargets.length===0,a.tinyTargets);record(`${name}_NO_UNREADABLY_TINY_TEXT`,a.tinyText.length===0,a.tinyText);}
try{
 previewServer=await preview({preview:{host:'127.0.0.1',port:4173,strictPort:false}});const addr=previewServer.httpServer.address();const url=`http://127.0.0.1:${addr.port}/`;browser=await chromium.launch({executablePath:EXECUTABLE,headless:true,args:['--no-sandbox','--disable-gpu']});const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'ar-SA'});const page=await context.newPage();page.setDefaultTimeout(6000);const consoleErrors=[],pageErrors=[];page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('pageerror',e=>pageErrors.push(e.message));await page.goto(url,{waitUntil:'domcontentloaded'});await page.locator('#root').waitFor({state:'attached'});await page.waitForTimeout(250);
 record('ARABIC_RTL_DEFAULT',(await page.locator('html').getAttribute('dir'))==='rtl');record('APP_HAS_MEANINGFUL_CONTENT',(await page.locator('body').innerText()).trim().length>500);
 const landmarks=await page.evaluate(()=>({headings:document.querySelectorAll('h1,h2,h3,h4,h5,h6,[role="heading"]').length,buttons:document.querySelectorAll('button,[role="button"]').length,inputs:document.querySelectorAll('input,select,textarea').length}));record('INFORMATION_HIERARCHY_HAS_HEADINGS',landmarks.headings>0,landmarks);record('CORE_INTERACTION_SURFACE_PRESENT',landmarks.buttons>0&&landmarks.inputs>0,landmarks);
 const unlabeled=await page.evaluate(()=>{const v=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.visibility!=='hidden'&&s.display!=='none'&&r.width>0&&r.height>0};return[...document.querySelectorAll('input,select,textarea')].filter(v).filter(e=>{const a=e.getAttribute('aria-label')||e.getAttribute('aria-labelledby')||e.getAttribute('title'),id=e.id,ex=id&&document.querySelector(`label[for="${CSS.escape(id)}"]`),w=e.closest('label');return !a&&!ex&&!w}).map(e=>({tag:e.tagName,type:e.getAttribute('type'),name:e.getAttribute('name'),placeholder:e.getAttribute('placeholder')})).slice(0,30)});record('FORM_CONTROLS_HAVE_ACCESSIBLE_LABELS',unlabeled.length===0,unlabeled);
 const emptyButtons=await page.evaluate(()=>[...document.querySelectorAll('button,[role="button"]')].filter(e=>{const r=e.getBoundingClientRect();if(r.width<=0||r.height<=0)return false;return !(e.innerText||e.getAttribute('aria-label')||e.getAttribute('title')||'').trim()}).map(e=>e.outerHTML.slice(0,180)).slice(0,20));record('BUTTONS_HAVE_DISCERNIBLE_NAMES',emptyButtons.length===0,emptyButtons);
 const focusSequence=[];for(let i=0;i<12;i++){await page.keyboard.press('Tab');const a=await page.evaluate(()=>{const e=document.activeElement;if(!e||e===document.body)return null;const s=getComputedStyle(e);return{tag:e.tagName,text:(e.innerText||e.getAttribute('aria-label')||e.getAttribute('name')||'').trim().slice(0,60),outlineStyle:s.outlineStyle,outlineWidth:s.outlineWidth,boxShadow:s.boxShadow}});if(a)focusSequence.push(a)}record('KEYBOARD_TAB_NAVIGATION_WORKS',focusSequence.length>=5,focusSequence);const vf=focusSequence.filter(x=>(x.outlineStyle&&x.outlineStyle!=='none'&&x.outlineWidth!=='0px')||(x.boxShadow&&x.boxShadow!=='none')).length;record('KEYBOARD_FOCUS_IS_VISIBLE',vf>=Math.min(3,focusSequence.length),{visibleFocusCount:vf,focusSequence});
 // Navigation is a state transition, not necessarily a body-text mutation. Verify the clicked tab becomes selected/current.
 for(const label of ['مبنى قائم','أرض + تطوير','التدفقات النقدية','تحليل الحساسية','لوحة المؤشرات']){const l=page.getByText(label,{exact:true}).first(),exists=await l.count();record(`NAV_${label}_PRESENT`,exists>0);if(exists){await l.click();await page.waitForTimeout(200);const state=await l.evaluate(e=>({ariaSelected:e.getAttribute('aria-selected'),ariaCurrent:e.getAttribute('aria-current'),pressed:e.getAttribute('aria-pressed'),className:e.className||'',parentClass:e.parentElement?.className||''}));const selected=state.ariaSelected==='true'||state.ariaCurrent==='page'||state.ariaCurrent==='true'||state.pressed==='true'||/active|selected|bg-\[#8a7440\]|text-white/.test(`${state.className} ${state.parentClass}`);record(`NAV_${label}_RESPONDS`,selected,state);}}
 // P1-07: fresh New Deal is deliberately fail-closed.
 await page.getByText('مبنى قائم',{exact:true}).first().click();await page.waitForTimeout(200);const blank=await page.locator('body').innerText();record('NEW_DEAL_FAIL_CLOSED',!LEGACY_VERDICT_RE.test(blank),{legacyVerdict:LEGACY_VERDICT_RE.test(blank)});
 // UX feedback and deterministic analytical-state checks require an explicit reference fixture.
 await loadReferenceDeal(page,/مبنى أبو بكر الصديق/);const editable=page.locator('input[type="text"], input[inputmode="decimal"], input[type="number"]').first();if(await editable.count()){const original=await editable.inputValue(),before=await page.locator('body').innerText();await editable.fill('123456');await editable.blur();await page.waitForTimeout(250);const after=await page.locator('body').innerText();record('INPUT_EDIT_IS_PERSISTED_VISIBLY',(await editable.inputValue())==='123456');record('INPUT_EDIT_PRODUCES_FEEDBACK',after!==before);await editable.fill(original||'1');await editable.blur();}else{record('INPUT_EDIT_IS_PERSISTED_VISIBLY',false,'No editable numeric/text input found');record('INPUT_EDIT_PRODUCES_FEEDBACK',false,'No editable numeric/text input found');}
 const exitCap=await enterExplicitBuildingExitCap(page,'8.5');record('V2_EXPLICIT_EXIT_CAP_CAN_BE_ENTERED',(await exitCap.inputValue())==='8.5',{value:await exitCap.inputValue()});await page.getByText('لوحة المؤشرات',{exact:true}).first().click();await page.waitForTimeout(200);const dashboard=await page.locator('body').innerText();const safe=/حالة تحليلية مواتية|حالة تحليلية مشروطة|مخاطر تحليلية مرتفعة|تعليق التحليل لحين استكمال الأدلة|يتطلب مراجعة مختص مرخص/.test(dashboard),imperative=LEGACY_VERDICT_RE.test(dashboard);record('DECISION_LANGUAGE_IS_NON_IMPERATIVE',safe&&!imperative,{safeLabel:safe,imperative});
 await viewportAudit(page,'MOBILE_390',390,844);await viewportAudit(page,'TABLET_768',768,1024);await viewportAudit(page,'DESKTOP_1440',1440,900);const motion=await page.emulateMedia({reducedMotion:'reduce'}).then(async()=>page.evaluate(()=>[...document.querySelectorAll('*')].filter(e=>{const s=getComputedStyle(e);return parseFloat(s.animationDuration)>0||parseFloat(s.transitionDuration)>0}).slice(0,30).map(e=>({tag:e.tagName,animation:getComputedStyle(e).animationDuration,transition:getComputedStyle(e).transitionDuration}))));record('REDUCED_MOTION_DOES_NOT_BREAK_UI',(await page.locator('#root').innerHTML()).length>100,motion);results.consoleErrors=consoleErrors;results.pageErrors=pageErrors;record('NO_PAGE_ERRORS_DURING_UX_JOURNEY',pageErrors.length===0,pageErrors.slice(0,5));record('NO_CONSOLE_ERRORS_DURING_UX_JOURNEY',consoleErrors.length===0,consoleErrors.slice(0,5));
}catch(e){failed=true;results.fatalError=e.message}finally{if(browser)await browser.close();if(previewServer)await new Promise(r=>previewServer.httpServer.close(r));results.totalChecks=results.checks.length;results.passedChecks=results.checks.filter(x=>x.status==='PASS').length;results.failedChecks=results.checks.filter(x=>x.status==='FAIL').length;results.result=failed||results.failedChecks>0?'FAIL':'PASS';results.caveat='Automated UX checks validate observable usability/accessibility heuristics and critical journeys. They do not replace moderated usability testing with representative real users.';fs.writeFileSync(`${EVIDENCE_DIR}/ux-experience-results.json`,JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));process.exit(results.result==='PASS'?0:1);}
