import { preview } from 'vite';
import { chromium } from 'playwright';
import fs from 'fs';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { findChromiumExecutable } = require('../config/paths');
const EXECUTABLE=findChromiumExecutable(),EVIDENCE_DIR='runtime-evidence/deep-platform';fs.mkdirSync(EVIDENCE_DIR,{recursive:true});
const report={suite:'UX_TASK_BASED_SCENARIOS_V1',tasks:[],browserErrors:[],consoleErrors:[]};let previewServer=null,browser=null,failed=false;
async function runTask(name,page,taskFn){const started=Date.now();let actions=0;const act=async fn=>{actions+=1;return fn()};try{const details=await taskFn(act);report.tasks.push({name,status:'PASS',actions,elapsedMs:Date.now()-started,details:details||null})}catch(error){failed=true;report.tasks.push({name,status:'FAIL',actions,elapsedMs:Date.now()-started,error:error.message})}}
async function safeDecisionVisible(page){const text=await page.locator('body').innerText(),safe=/حالة تحليلية مواتية|حالة تحليلية مشروطة|مخاطر تحليلية مرتفعة|تعليق التحليل لحين استكمال الأدلة|يتطلب مراجعة مختص مرخص/.test(text),imperative=/يوصى بالشراء|لا يوصى بالشراء/.test(text);if(!safe||imperative)throw new Error(`decision language unsafe or unclear: safe=${safe} imperative=${imperative}`);return{safe,imperative}}
async function loadReferenceDeal(page,act,nameRe){await act(()=>page.getByTitle('الصفقات المحفوظة').click());await page.waitForTimeout(200);await act(()=>page.getByRole('button',{name:nameRe}).first().click());await page.waitForTimeout(300)}
async function enterExplicitBuildingExitCap(page,act,value='8.5'){const b=page.getByRole('button',{name:/افتراضات التقييم والاستثمار/}).first(),s=b.locator('xpath=ancestor::div[contains(@class,"rounded-2xl") and contains(@class,"overflow-hidden")][1]'),body=s.locator('.rf-accordion-body').first();if(!((await body.getAttribute('class'))||'').split(/\s+/).includes('open')){await act(()=>b.click());await page.waitForTimeout(180)}const x=page.getByText('معدل رسملة الخروج',{exact:true}).locator('xpath=ancestor::label[1]').locator('input').first();await act(()=>x.fill(value));await act(()=>x.blur());await page.waitForTimeout(220);if((await x.inputValue())!==value)throw new Error(`explicit exit cap did not persist visibly: ${await x.inputValue()}`);return x}
try{
 previewServer=await preview({preview:{host:'127.0.0.1',port:4173,strictPort:false}});const addr=previewServer.httpServer.address(),url=`http://127.0.0.1:${addr.port}/`;browser=await chromium.launch({executablePath:EXECUTABLE,headless:true,args:['--no-sandbox','--disable-gpu']});const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'ar-SA'}),page=await context.newPage();page.setDefaultTimeout(7000);page.on('pageerror',e=>report.browserErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text())});await page.goto(url,{waitUntil:'domcontentloaded'});await page.locator('#root').waitFor({state:'attached'});await page.waitForTimeout(250);
 await runTask('NEW_DEAL_FAIL_CLOSED',page,async act=>{await act(()=>page.getByText('مبنى قائم',{exact:true}).first().click());await page.waitForTimeout(180);const text=await page.locator('body').innerText(),imperative=/يوصى بالشراء|لا يوصى بالشراء/.test(text);if(imperative)throw new Error('fresh New Deal exposed legacy imperative verdict');return{imperative,taskGoal:'verify blank New Deal remains fail-closed'}});
 await runTask('NOVICE_EXISTING_BUILDING_REVIEW',page,async act=>{await loadReferenceDeal(page,act,/مبنى أبو بكر الصديق/);const input=page.locator('input[type="text"], input[inputmode="decimal"]').first(),original=await input.inputValue();await act(()=>input.fill('120'));await act(()=>input.blur());await page.waitForTimeout(200);if((await input.inputValue())!=='120')throw new Error('edited building input did not persist visibly');const exitCap=await enterExplicitBuildingExitCap(page,act,'8.5');await act(()=>page.getByText('لوحة المؤشرات',{exact:true}).first().click());await page.waitForTimeout(200);const decision=await safeDecisionVisible(page);await act(()=>page.getByText('التدفقات النقدية',{exact:true}).first().click());await page.waitForTimeout(200);if((await page.locator('body').innerText()).length<500)throw new Error('cash-flow view lacks meaningful visible content');return{decision,exitCap:await exitCap.inputValue(),original,taskGoal:'edit reference assumptions, read analytical state, inspect cash flow'}});
 await runTask('NOVICE_LAND_DEVELOPMENT_REVIEW',page,async act=>{await loadReferenceDeal(page,act,/أرض الوادي/);const inputs=page.locator('input[type="text"], input[inputmode="decimal"]');if((await inputs.count())<2)throw new Error('land workflow does not expose enough editable inputs');const first=inputs.nth(0),second=inputs.nth(1);await act(()=>first.fill('35'));await act(()=>first.blur());await act(()=>second.fill('65'));await act(()=>second.blur());await page.waitForTimeout(200);await act(()=>page.getByText('تحليل الحساسية',{exact:true}).first().click());await page.waitForTimeout(300);if((await page.locator('svg').count())===0)throw new Error('sensitivity view has no chart/visual output');await act(()=>page.getByText('لوحة المؤشرات',{exact:true}).first().click());await page.waitForTimeout(200);const decision=await safeDecisionVisible(page);return{decision,taskGoal:'edit reference land assumptions, inspect sensitivity, read analytical state'}});
 await runTask('FINANCING_DISCOVERY_AND_REVERSIBILITY',page,async act=>{await loadReferenceDeal(page,act,/مبنى أبو بكر الصديق/);const toggle=page.getByRole('switch',{name:'تفعيل الرافعة المالية'}).first();if((await toggle.count())===0)throw new Error('financing toggle cannot be discovered by accessible name');const section=toggle.locator('xpath=ancestor::div[contains(@class,"rounded-2xl") and contains(@class,"overflow-hidden")][1]'),body=section.locator('.rf-accordion-body').first();if((await body.count())===0)throw new Error('financing accordion body could not be resolved');if(!((await body.getAttribute('class'))||'').split(/\s+/).includes('open')){await act(()=>section.locator(':scope > button').first().click());await page.waitForTimeout(220)}await toggle.scrollIntoViewIfNeeded();const before=await toggle.getAttribute('aria-checked');await act(()=>toggle.click());await page.waitForTimeout(180);const after=await toggle.getAttribute('aria-checked');if(before===after)throw new Error('financing toggle did not communicate state change');await act(()=>toggle.click());await page.waitForTimeout(120);const restored=await toggle.getAttribute('aria-checked');if(restored!==before)throw new Error('financing toggle was not reversible');return{before,after,restored,sectionOpened:true}});
 await runTask('MOBILE_CRITICAL_PATH',page,async act=>{await act(()=>page.setViewportSize({width:390,height:844}));await loadReferenceDeal(page,act,/أرض الوادي/);await act(()=>page.getByText('تحليل الحساسية',{exact:true}).first().click());await page.waitForTimeout(250);await act(()=>page.getByText('لوحة المؤشرات',{exact:true}).first().click());await page.waitForTimeout(200);await safeDecisionVisible(page);const dims=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth}));if(dims.scrollWidth>dims.clientWidth+5)throw new Error(`mobile horizontal overflow ${JSON.stringify(dims)}`);return{...dims,taskGoal:'complete critical reference-deal review path on phone viewport'}});
 await runTask('LANGUAGE_DIRECTION_SWITCH',page,async act=>{await act(()=>page.setViewportSize({width:1440,height:900}));const en=page.getByRole('button',{name:'الإنجليزية'}).first();if((await en.count())===0)throw new Error('English language control not discoverable');await act(()=>en.click());await page.waitForTimeout(220);const dirEn=await page.locator('html').getAttribute('dir'),langEn=await page.locator('html').getAttribute('lang');if(dirEn!=='ltr'||langEn!=='en')throw new Error(`English direction/lang invalid: ${dirEn}/${langEn}`);const ar=page.getByTitle('التبديل إلى العربية').first();if((await ar.count())===0)throw new Error('Arabic language control not discoverable');await act(()=>ar.click());await page.waitForTimeout(220);const dirAr=await page.locator('html').getAttribute('dir'),langAr=await page.locator('html').getAttribute('lang');if(dirAr!=='rtl'||langAr!=='ar-SA')throw new Error(`Arabic direction/lang invalid: ${dirAr}/${langAr}`);return{dirEn,langEn,dirAr,langAr}});
 if(report.browserErrors.length||report.consoleErrors.length)failed=true;
}catch(error){failed=true;report.fatalError=error.message}finally{if(browser)await browser.close();if(previewServer)await new Promise(r=>previewServer.httpServer.close(r));report.totalTasks=report.tasks.length;report.passedTasks=report.tasks.filter(x=>x.status==='PASS').length;report.failedTasks=report.tasks.filter(x=>x.status==='FAIL').length;report.totalActions=report.tasks.reduce((s,x)=>s+(x.actions||0),0);report.result=failed||report.failedTasks>0?'FAIL':'PASS';report.interpretation='Task-based automation measures observable path completion, discoverability, feedback, reversibility, mobile continuity, and language-direction switching. It does not replace moderated usability sessions with representative users or measure subjective satisfaction.';fs.writeFileSync(`${EVIDENCE_DIR}/ux-task-scenarios-results.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));process.exit(report.result==='PASS'?0:1)}
