'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { createRequire } = require('node:module');
const { JSDOM } = require('jsdom');
const gold = require('../reference/RE-GOLD-baseline.json');
const { V2_APPROVED_ASSUMPTIONS } = require('../../src/assumptions/assumption-model');
const { buildPersonalFinancialStudy, verifyPersonalFinancialStudy, htmlFinancialStudy } = require('../../src/app/personal-financial-study');
const { updateValuationEditorDraft, validateValuationEditorDraft, copyValuationEditorDraft, rebaseValuationEditorDraft } = require('../../src/app/valuation-editor-draft');
const { advancedDraftFromValuationCase } = require('../../src/app/valuation-advanced-draft');
const { emptyValuationCaseDraft } = require('../../src/app/valuation-case-draft');
const { describeDiagnostic } = require('../../src/i18n/diagnostic-presentation');
const { validateSavedDealRecord } = require('../../src/validation/saved-deal-schema');
const { buildExportPayload, planRestore } = require('../../src/storage/saved-deals-backup');
let checks = 0;
const ok = (value, message) => { assert.ok(value, message); checks++; };
const eq = (actual, expected, message) => { assert.deepEqual(actual, expected, message); checks++; };
const close = (actual, expected, tolerance, message) => ok(Math.abs(actual - expected) < tolerance, message);
const make = (mode, inputs, version = 'LEGACY') => buildPersonalFinancialStudy({ mode, inputs, assumptionModelVersion: version,
  generatedAt: '2026-10-10T01:27:00Z', dealName: 'AUDIT ONLY 20261010 OFFICE / عقار' });

(async () => {
  const building = { ...gold['RE-GOLD-002_existing_building'].inputs };
  const land = { ...gold['RE-GOLD-001_land_development'].inputs };
  const b = make('building', building), l = make('land', land);
  ok(verifyPersonalFinancialStudy(b) && verifyPersonalFinancialStudy(l), 'both modes produce verified current-input reports');
  eq(b.financial.inputs, building, 'no mutation or alternate financial inputs');
  close(b.financial.payback.simpleCostOverFirstOperatingNoiYears, 10.308456444915265, 1e-9, 'independent fixed-NOI cost ratio');
  eq(b.financial.payback.cumulativeOperatingWithinStudyYears, null, 'five operating years do not recover purchase');
  eq(b.financial.payback.cumulativeWithTerminalSaleYears, 5, 'sale-dependent recovery occurs at year five, not interpolated before sale');
  eq(b.financial.payback.engineOperatingHorizonYears, 30, 'engine horizon disclosed separately from five-year hold');
  const growing = make('building', { ...building, rentGrowthRate: 0.05 });
  ok(growing.financial.payback.engineCumulativeOperatingYears < growing.financial.payback.simpleCostOverFirstOperatingNoiYears,
    'growing cumulative recovery is not mislabeled as fixed-NOI ratio');
  const lv2 = make('land', { ...land, ...V2_APPROVED_ASSUMPTIONS }, 'V2');
  close(lv2.financial.results.maxJustifiedLandPricePerSqm, 13603.01, 1e-8, 'F02 audited calendar boundary remains intact');
  close(lv2.financial.results.firstOperatingYearNOI, 11468096.64, 1e-6, 'F07 does not replace financial engine');
  eq(l.financial.annualCashflows[1].operatingNoi, 0, 'no operating income during construction');
  eq(l.financial.annualCashflows.length, 13, 'year zero, two construction years and ten operating years retained');
  eq(l.financial.experiments.sensitivity.length, 3, 'land rental, construction and purchase sensitivities calculated');
  ok(l.financial.experiments.sensitivity.every(s => s.low.metrics.irr !== s.high.metrics.irr), 'sensitivity changes actual canonical results');
  eq(l.financial.experiments.scenarios[0].metrics.irr, l.financial.results.irr, 'base scenario is the original financial result');
  ok(l.financial.experiments.scenarios[2].metrics.npv < l.financial.results.npv, 'compound downside reduces actual NPV');
  eq(b.financial.experiments.sensitivity[2].high.appliedChanges[0].effective, 1, 'occupancy bounded at actual 100% with disclosure');
  ok(b.financial.experiments.sensitivity[2].high.appliedChanges[0].boundaryLimited, 'boundary clipping explicitly recorded');
  const invalid = make('building', { ...building, buildingPrice: -1 });
  eq(invalid.financial.inputs.buildingPrice, -1, 'invalid original price preserved');
  eq(invalid.financial.results, null, 'invalid current inputs cannot export a prior valid result');
  eq(invalid.financial.status, 'INPUTS_INVALID', 'invalid financial draft explicit');
  eq(invalid.financial.annualCashflows, [], 'invalid draft has no invented annual cashflows');
  const tampered = JSON.parse(JSON.stringify(b)); tampered.financial.results.NOI += 1;
  ok(!verifyPersonalFinancialStudy(tampered), 'editing a reported metric invalidates its fingerprint');
  const html = htmlFinancialStudy(b);
  ok(html.includes('التدفقات السنوية') && html.includes('قبل احتياطي الإحلال') && html.includes('سيناريوهات اختبار افتراضية'), 'financial report includes cashflows, reserve basis and scenarios');
  ok(html.includes('غير متحقق ضمن مدة الدراسة') && html.includes('dir="rtl"'), 'Arabic report preserves unavailable operating payback and RTL');
  ok(html.includes(b.inputFingerprintSha256) && html.includes(b.reportHashSha256), 'input and report fingerprints included');
  const unsafe = buildPersonalFinancialStudy({ mode: 'building', inputs: building, assumptionModelVersion: 'LEGACY', dealName: '<script>alert(1)</script>' });
  ok(!htmlFinancialStudy(unsafe).includes('<script>') && htmlFinancialStudy(unsafe).includes('&lt;script&gt;'), 'untrusted user name is escaped in standalone HTML');
  const zero = make('building', { ...building, commissionRate: 0 });
  eq(zero.financial.inputs.commissionRate, 0, 'real zero stays distinct from missing');
  eq(describeDiagnostic('EVIDENCE_QUALITY_POLICY_REQUIRED').code, 'EVIDENCE_QUALITY_POLICY_REQUIRED', 'original hold code retained');
  ok(describeDiagnostic('EVIDENCE_QUALITY_POLICY_REQUIRED').message.includes('الأدلة'), 'known hold has a semantic Arabic explanation');
  eq(describeDiagnostic('UNREGISTERED_REASON_X').code, 'UNREGISTERED_REASON_X', 'unknown diagnostic cannot be hidden');
  const base = emptyValuationCaseDraft(); base.projectId = 'DRAFT-UNAPPLIED';
  const draft = updateValuationEditorDraft(null, 'base', base);
  eq(draft.status, 'UNAPPLIED_NOT_VERIFIED', 'partial configuration never becomes an approval');
  const copied = copyValuationEditorDraft(draft); copied.base.projectId = 'CHANGED';
  eq(draft.base.projectId, 'DRAFT-UNAPPLIED', 'copied draft does not mutate the source');
  const advancedDraft = advancedDraftFromValuationCase(null);
  advancedDraft.marketComparable.subjectArea = 'UNAPPLIED-AREA';
  const combined = updateValuationEditorDraft(draft, 'advanced', advancedDraft);
  const newCase = { projectId: 'APPLIED', marketComparableInput: { currency: 'SAR' } };
  const retainedBase = rebaseValuationEditorDraft(combined, 'advanced', newCase);
  eq(retainedBase.base.projectId, 'DRAFT-UNAPPLIED', 'applying advanced settings retains unapplied base edits');
  eq(retainedBase.base.preservedAdvanced.marketComparableInput, newCase.marketComparableInput, 'later base apply cannot overwrite newly applied advanced settings');
  eq(rebaseValuationEditorDraft(combined, 'base', newCase).advanced.marketComparable.subjectArea, 'UNAPPLIED-AREA', 'applying base retains unapplied advanced edits');
  eq(rebaseValuationEditorDraft(draft, 'base', newCase), null, 'successful apply removes only the applied editor group');
  eq(rebaseValuationEditorDraft(combined, 'base', null), null, 'explicit disable clears the editor draft');
  const deal = { id: 'audit-f06', name: 'AUDIT ONLY 20261010 OFFICE', mode: 'building', inputs: building, savedAt: '2026-10-10', valuationEditorDraft: draft };
  eq(validateSavedDealRecord(deal), deal, 'partial editor draft persists without applying its configuration');
  const provider = { get: async key => key === 'deal:audit-f06' ? JSON.stringify(deal) : null };
  const backup = await buildExportPayload([{ id: deal.id }], provider);
  eq(backup.deals[0].valuationEditorDraft, draft, 'backup preserves unapplied editor data');
  const restored = planRestore(backup, [], new Map()).toWrite[0].record;
  eq(restored.valuationEditorDraft, draft, 'restore preserves full partial draft');
  eq(restored.name, deal.name, 'backup and restore preserve English user names byte for byte');
  assert.throws(() => validateValuationEditorDraft({ ...draft, status: 'APPROVED' })); checks++;
  assert.throws(() => validateValuationEditorDraft({ ...draft, base: { ...base, projectId: {} } })); checks++;
  assert.throws(() => validateSavedDealRecord({ ...deal, mode: 'land' })); checks++;
  const dom = new JSDOM('<div id="root"><button><span data-user-content><b>AUDIT ONLY 20261010 OFFICE</b></span></button><span data-diagnostic-content><code>UNREGISTERED_REASON_X</code></span><span id="label">Project</span></div>');
  const file = path.resolve(__dirname, '../../src/components/StrictArabicSurfaceGuard.jsx');
  const source = fs.readFileSync(file, 'utf8').replace(/^import React,.*\n/m, '').replace('export default function ', 'function ').replace(/export \{[^}]+\};/, '');
  const context = { require: createRequire(file), document: dom.window.document, NodeFilter: dom.window.NodeFilter };
  vm.runInNewContext(source + '\nprocessTree(document.getElementById("root"));', context);
  eq(dom.window.document.querySelector('[data-user-content]').textContent, deal.name, 'Arabic DOM guard leaves nested user data unchanged');
  eq(dom.window.document.querySelector('code').textContent, 'UNREGISTERED_REASON_X', 'Arabic DOM guard leaves original diagnostic code intact');
  eq(dom.window.document.getElementById('label').textContent, 'المشروع', 'system labels still translate normally');
  console.log('AUDIT_20261010_F03_F07=PASS checks=' + checks);
})().catch(error => { console.error(error); process.exitCode = 1; });
