'use strict';

module.exports = {
  ...require('./contracts'),
  ...require('./market-comparables'),
  ...require('./income-capitalization'),
  ...require('./cost-approach'),
  ...require('./residual-approach'),
  ...require('./reconciliation'),
  ...require('./planner'),
  ...require('./evidence-quality'),
  ...require('./reason-codes'),
  ...require('./valuation-request'),
  ...require('./orchestrator'),
  ...require('./saved-deal-extension'),
  ...require('./cap-rate-governance'),
  ...require('./reconciled-direct-capitalization'),
  ...require('./governed-dcf'),
  ...require('./workflow-reconciliation'),
  ...require('./golden-validation'),
  ...require('./stress-testing'),
  ...require('./monte-carlo-risk'),
  ...require('./hbu-land-bid'),
  ...require('./portfolio-decision-cockpit'),
  ...require('./adapters/industrial-logistics'),
  ...require('./adapters/existing-building-ui'),
};
