'use strict';

const VALUATION_STAGE_STATUS = Object.freeze({
  READY_FOR_DECISION_CONTROL: 'READY_FOR_DECISION_CONTROL',
  HOLD_INPUTS: 'HOLD_INPUTS',
  HOLD_EVIDENCE: 'HOLD_EVIDENCE',
  HOLD_POLICY: 'HOLD_POLICY',
  UNAVAILABLE: 'UNAVAILABLE',
});

const METHOD_STATE = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  HOLD: 'HOLD',
  UNAVAILABLE: 'UNAVAILABLE',
});

const VALUATION_REASON_CODE = Object.freeze({
  METHOD_NOT_APPLICABLE: 'METHOD_NOT_APPLICABLE',
  ASSET_ADAPTER_REQUIRED: 'ASSET_ADAPTER_REQUIRED',
  METHOD_INPUTS_REQUIRED: 'METHOD_INPUTS_REQUIRED',
  METHOD_INPUT_INVALID: 'METHOD_INPUT_INVALID',
  METHOD_EVIDENCE_CONFLICT: 'METHOD_EVIDENCE_CONFLICT',
  EVIDENCE_QUALITY_POLICY_REQUIRED: 'EVIDENCE_QUALITY_POLICY_REQUIRED',
  EVIDENCE_QUALITY_HOLD: 'EVIDENCE_QUALITY_HOLD',
  MIXED_USE_COMPONENTS_REQUIRED: 'MIXED_USE_COMPONENTS_REQUIRED',
  NO_QUALIFIED_VALUATION_METHOD: 'NO_QUALIFIED_VALUATION_METHOD',
  SINGLE_METHOD_ACCEPTANCE_POLICY_REQUIRED: 'SINGLE_METHOD_ACCEPTANCE_POLICY_REQUIRED',
  SINGLE_METHOD_ACCEPTANCE_POLICY_MISMATCH: 'SINGLE_METHOD_ACCEPTANCE_POLICY_MISMATCH',
  RECONCILIATION_POLICY_REQUIRED: 'RECONCILIATION_POLICY_REQUIRED',
  RECONCILIATION_METHOD_SET_MISMATCH: 'RECONCILIATION_METHOD_SET_MISMATCH',
  RECONCILIATION_INPUT_METHOD_HOLD: 'RECONCILIATION_INPUT_METHOD_HOLD',
  RECONCILIATION_BASIS_MISMATCH: 'RECONCILIATION_BASIS_MISMATCH',
  RECONCILIATION_CURRENCY_MISMATCH: 'RECONCILIATION_CURRENCY_MISMATCH',
  RECONCILIATION_DATE_MISMATCH: 'RECONCILIATION_DATE_MISMATCH',
  RECONCILIATION_DISPERSION_HOLD: 'RECONCILIATION_DISPERSION_HOLD',
  RECONCILIATION_UNKNOWN_HOLD: 'RECONCILIATION_UNKNOWN_HOLD',
});

module.exports = {
  VALUATION_STAGE_STATUS,
  METHOD_STATE,
  VALUATION_REASON_CODE,
};
