'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const {STATUS,EXTERNAL_STATUS,createHistoricalReplayPlan,verifyHistoricalReplayPlan,createExternalHistoricalReplayRecord,verifyExternalHistoricalReplayRecord,evaluateInternalHistoricalReplayReadiness,evaluateExternalHistoricalReplayForGateIngestion}=require('../../src/replay/historical-replay-readiness');
const ROOT=path.join(__dirname,'..','..'),SHA='1234567890abcdef1234567890abcdef12345678',AS_OF='2026-10-04T12:00:00Z';let checks=0;const check=f=>{f();checks++;},read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const measures=[{measureId:'DECISION_OUTCOME_COMPARISON',definitionRef:'PREDECLARED-MEASURE-DECISION-OUTCOME'},{measureId:'VALUE_DEVIATION_OBSERVATION',definitionRef:'PREDECLARED-MEASURE-VALUE-DEVIATION'}];
function plan(o={}){return createHistoricalReplayPlan({candidateHeadSha:SHA,productScopeRef:'STARTAK-REAL-ESTATE-C51-SCOPE',replayMethodRef:'HISTORICAL-REPLAY-METHOD-V1',predeclaredMeasures:measures,preparedAt:'2026-10-04T08:00:00Z',validUntil:'2026-10-11T08:00:00Z',...o});}
function record(status,o={}){const x={evidenceId:'HISTORICAL_REPLAY_EVIDENCE',candidateHeadSha:SHA,status};if(status===EXTERNAL_STATUS.NOT_SUPPLIED)x.reasonCode='REAL_HISTORICAL_CASES_NOT_SUPPLIED';else Object.assign(x,{evidenceRef:'STRUCTURAL-TEST-HISTORICAL-PACK',evidenceHashSha256:'b'.repeat(64),verifiedByRef:'STRUCTURAL-TEST-INDEPENDENT-PROFESSIONAL',verifiedAt:'2026-10-04T10:00:00Z',validUntil:'2026-10-10T10:00:00Z',replayMethodRef:'HISTORICAL-REPLAY-METHOD-V1',predeclaredMeasuresRef:'PREDECLARED-MEASURES-REGISTER-V1',cases:[{caseId:'REAL-CASE-STRUCTURAL-1',provenanceRef:'REAL-CASE-PROVENANCE-REF',historicalObservationDate:'2025-01-10T00:00:00Z',historicalTruthOutcomeRef:'HISTORICAL-TRUTH-REF',systemReplayResultRef:'SYSTEM-REPLAY-RESULT-REF',deviationReviewRef:'INDEPENDENT-DEVIATION-REVIEW-REF',synthetic:false}],materialDeviationDispositionRef:'MATERIAL-DEVIATION-DISPOSITION-REF'});if(status===EXTERNAL_STATUS.REJECTED)x.reasonCode='MATERIAL_REPLAY_PERFORMANCE_REJECTED';return createExternalHistoricalReplayRecord({...x,...o});}
const p=plan();check(()=>assert(verifyHistoricalReplayPlan(p)));check(()=>assert.strictEqual(p.syntheticCasesAcceptedAsHistoricalEvidence,false));check(()=>assert.strictEqual(p.historicalReplayApproved,false));const i=evaluateInternalHistoricalReplayReadiness({replayPlan:p,asOf:AS_OF});check(()=>assert.strictEqual(i.status,STATUS.READY_FOR_INDEPENDENT_HISTORICAL_REPLAY));check(()=>assert.strictEqual(i.internalEngineeringReady,true));check(()=>assert.strictEqual(i.historicalReplayApproved,false));
check(()=>assert.throws(()=>plan({candidateHeadSha:'bad'}),/40-character/));check(()=>assert.throws(()=>plan({predeclaredMeasures:[]}),/PREDECLARED_MEASURES/));check(()=>assert.throws(()=>plan({predeclaredMeasures:[measures[0],measures[0]]}),/DUPLICATE/));
const stale=plan({validUntil:'2026-10-04T09:00:00Z'});check(()=>assert.strictEqual(evaluateInternalHistoricalReplayReadiness({replayPlan:stale,asOf:AS_OF}).status,STATUS.HOLD_WINDOW));const tampered={...p,replayMethodRef:'TAMPERED'};check(()=>assert.strictEqual(evaluateInternalHistoricalReplayReadiness({replayPlan:tampered,asOf:AS_OF}).status,STATUS.HOLD_INTEGRITY));
const ns=record(EXTERNAL_STATUS.NOT_SUPPLIED);check(()=>assert(verifyExternalHistoricalReplayRecord(ns)));const nr=evaluateExternalHistoricalReplayForGateIngestion({replayPlan:p,replayRecord:ns,asOf:AS_OF});check(()=>assert.strictEqual(nr.status,STATUS.HOLD_EXTERNAL_HISTORICAL_REPLAY));check(()=>assert.strictEqual(nr.readyForC30GateIngestion,false));check(()=>assert.strictEqual(nr.historicalReplayApproved,false));check(()=>assert.throws(()=>record(EXTERNAL_STATUS.NOT_SUPPLIED,{evidenceRef:'FAKE'}),/MUST_NOT_CARRY/));
check(()=>assert.throws(()=>record(EXTERNAL_STATUS.SUPPLIED_VERIFIED,{cases:[{caseId:'SYN',provenanceRef:'P',historicalObservationDate:'2025-01-01',historicalTruthOutcomeRef:'T',systemReplayResultRef:'R',deviationReviewRef:'D',synthetic:true}]}),/REAL_CASE_FIELDS_REQUIRED/));
const supplied=record(EXTERNAL_STATUS.SUPPLIED_VERIFIED);check(()=>assert(verifyExternalHistoricalReplayRecord(supplied)));const sr=evaluateExternalHistoricalReplayForGateIngestion({replayPlan:p,replayRecord:supplied,asOf:AS_OF});check(()=>assert.strictEqual(sr.status,STATUS.READY_FOR_C30_GATE_INGESTION));check(()=>assert.strictEqual(sr.readyForC30GateIngestion,true));check(()=>assert.strictEqual(sr.independentAuthorityStillMustBeValidatedByC30,true));check(()=>assert.strictEqual(sr.historicalReplayApproved,false));check(()=>assert.strictEqual(sr.deploymentAuthorized,false));check(()=>assert.strictEqual(sr.commercialGoLiveAuthorized,false));
const mismatch=record(EXTERNAL_STATUS.SUPPLIED_VERIFIED,{candidateHeadSha:'abcdefabcdefabcdefabcdefabcdefabcdefabcd'});check(()=>assert(evaluateExternalHistoricalReplayForGateIngestion({replayPlan:p,replayRecord:mismatch,asOf:AS_OF}).blockers.includes('C51_EXTERNAL_BINDING_MISMATCH:candidateHeadSha')));const method=record(EXTERNAL_STATUS.SUPPLIED_VERIFIED,{replayMethodRef:'OTHER-METHOD'});check(()=>assert(evaluateExternalHistoricalReplayForGateIngestion({replayPlan:p,replayRecord:method,asOf:AS_OF}).blockers.includes('C51_EXTERNAL_METHOD_MISMATCH')));
const rejected=record(EXTERNAL_STATUS.REJECTED);const rr=evaluateExternalHistoricalReplayForGateIngestion({replayPlan:p,replayRecord:rejected,asOf:AS_OF});check(()=>assert.strictEqual(rr.status,STATUS.REJECTED));check(()=>assert.strictEqual(rr.historicalReplayApproved,false));
const evidence=JSON.parse(read('release/evidence/c51-internal-historical-replay-readiness.json'));['historicalReplayEvidenceSupplied','gate550Satisfied','historicalReplayApproved','deploymentAuthorized','commercialGoLiveAuthorized'].forEach(f=>check(()=>assert.strictEqual(evidence[f],false)));const docs=read('docs/C51_INTERNAL_HISTORICAL_REPLAY_READINESS.md');check(()=>assert(docs.includes('synthetic cases are not historical evidence')));check(()=>assert(docs.includes('does not satisfy external gate #550')));check(()=>assert(docs.includes('no invented accuracy')));
const wf=read('.github/workflows/c51-internal-historical-replay-readiness.yml'),imm=/^\s*-?\s*uses:\s*[^\s@]+@[a-f0-9]{40}\s*$/i;wf.split(/\r?\n/).filter(l=>/^\s*-?\s*uses:/.test(l)).forEach(l=>check(()=>assert(imm.test(l))));check(()=>assert(wf.includes('C51_GATE_550_SATISFIED=FALSE'));check(()=>assert(wf.includes('C51_HISTORICAL_REPLAY_APPROVED=FALSE')));
console.log(`C51_INTERNAL_HISTORICAL_REPLAY_READINESS=PASS checks=${checks}`);console.log('C51_READY_FOR_INDEPENDENT_HISTORICAL_REPLAY=PASS');console.log('C51_GATE_550_SATISFIED=FALSE');console.log('C51_HISTORICAL_REPLAY_APPROVED=FALSE');console.log('C51_DEPLOYMENT_AUTHORIZED=FALSE');console.log('C51_COMMERCIAL_GO_LIVE_AUTHORIZED=FALSE');
