import React,{useEffect,useRef,useState} from 'react';
import DiagnosticText from './DiagnosticText.jsx';
const {describeDiagnostic}=require('../i18n/diagnostic-presentation');
const {useLocale}=require('../i18n/LocaleContext');
const {createStorageProvider}=require('../storage/create-storage-provider');
const {journalKey}=require('../storage/local-review-journal');
const {ACTION_STATUS}=require('../decision-actions');
const {gapRequirements,workspaceFingerprint,createLocalCaseAction,advanceLocalCaseAction,exportLocalCaseActions,restoreLocalCaseActions,localCaseActionRegister}=require('../decision-actions/local-case-actions');
const input='mt-1 w-full rounded border border-slate-600 bg-slate-950 p-2';
export default function CaseGapActionsPanel({workspace,onRegisterChange}){
 const {locale}=useLocale(),ar=locale==='ar-SA';const [entries,setEntries]=useState([]),[error,setError]=useState(null),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({section:gapRequirements(workspace)[0]?.section||'',ownerId:'',dueDate:'',actorId:'',evidenceRef:'',reviewNote:''});const fileRef=useRef();
 const key=journalKey({caseId:workspace.caseId,projectId:workspace.projectId,kind:'ACTIONS'})+':'+workspaceFingerprint(workspace);
 const publish=next=>{setEntries(next);onRegisterChange(localCaseActionRegister(workspace,next));};
 useEffect(()=>{let active=true;(async()=>{try{const raw=await createStorageProvider().get(key);if(raw&&active)publish(restoreLocalCaseActions(workspace,raw));}catch(e){if(active)setError(e.code||'LOCAL_RECORD_INVALID');}})();return()=>{active=false;};},[key]);
 async function persist(next){setBusy(true);try{const journal=exportLocalCaseActions(workspace,next);await createStorageProvider().set(key,JSON.stringify(journal));publish(next);setError(null);}catch(e){setError(e.code||'LOCAL_RECORD_INVALID');}finally{setBusy(false);}}
 function create(){try{const entry=createLocalCaseAction({workspace,...form,occurredAt:new Date().toISOString()});if(entries.some(e=>e.action.actionId===entry.action.actionId))throw Object.assign(new Error('LOCAL_RECORD_INVALID'),{code:'LOCAL_RECORD_INVALID'});void persist([...entries,entry]);}catch(e){setError(e.code||'LOCAL_RECORD_INVALID');}}
 function advance(entry,toStatus){try{const next=advanceLocalCaseAction({entry,toStatus,...form,occurredAt:new Date().toISOString()});void persist(entries.map(e=>e.action.actionId===next.action.actionId?next:e));}catch(e){setError(e.code||'LOCAL_RECORD_INVALID');}}
 function download(){const journal=exportLocalCaseActions(workspace,entries),url=URL.createObjectURL(new Blob([JSON.stringify(journal,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='startak-case-actions.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function restore(file){try{if(!file||file.size>2000000)throw Object.assign(new Error('LOCAL_RECORD_INVALID'),{code:'LOCAL_RECORD_INVALID'});await persist(restoreLocalCaseActions(workspace,await file.text()));}catch(e){setError(e.code||'LOCAL_RECORD_INVALID');}finally{fileRef.current.value='';}}
 return <section data-testid="case-gap-actions" className="mt-4 rounded-xl border border-slate-600 bg-[#101a2d] p-4 text-xs text-slate-200">
  <h2 className="font-semibold">{ar?'إجراءات إغلاق فجوات الحالة':'Case gap actions'}</h2>
  <p className="my-2 leading-6">{ar?'حدد المسؤول والموعد صراحة. الإغلاق المحلي يسجل مراجعة بشرية بمرجع دليل ومراجع مختلف عن المسؤول. إجراءات المختص المرخص تبقى معلقة حتى التحقق المؤسسي. إغلاق الإجراء لا يغلق بوابات الحالة أو يمنح قرارًا مهنيًا.':'Explicitly assign an owner and deadline. Local closure records a referenced human review by someone other than the owner. Licensed review stays held for institutional verification. Action closure does not approve case gates or professional release.'}</p>
  <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
   <label>{ar?'الفجوة':'Gap'}<select data-testid="case-action-gap" className={input} value={form.section} onChange={e=>setForm({...form,section:e.target.value})}>{gapRequirements(workspace).map(g=><option key={g.section} value={g.section}>{describeDiagnostic(g.code,locale).message}</option>)}</select></label>
   {[["ownerId",ar?'المسؤول عن الإجراء':'Action owner'],["dueDate",ar?'الموعد المستهدف':'Due date'],["actorId",ar?'اسم مسجل الإجراء أو المراجع':'Recorder or reviewer'],["evidenceRef",ar?'مرجع الدليل والصفحة':'Evidence and page reference'],["reviewNote",ar?'ملاحظة مراجعة الإغلاق':'Closure review note']].map(([key,label])=><label key={key}>{label}<input data-testid={`case-action-${key}`} type={key==='dueDate'?'date':'text'} maxLength="2000" className={input} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}
  </div>
  <div className="mt-3 flex flex-wrap gap-2"><button data-testid="create-case-action" type="button" disabled={busy||!form.section} onClick={create} className="rounded border border-sky-600 px-3 py-2 disabled:opacity-50">{ar?'إنشاء الإجراء وحفظه':'Create and save action'}</button><button type="button" disabled={busy||!entries.length} onClick={download} className="rounded border border-slate-600 px-3 py-2 disabled:opacity-50">{ar?'تصدير سجل الإجراءات':'Export actions'}</button><button type="button" disabled={busy} onClick={()=>fileRef.current.click()} className="rounded border border-slate-600 px-3 py-2">{ar?'استعادة سجل الحالة':'Restore case actions'}</button><input aria-label={ar?'سجل إجراءات الحالة':'Case action journal'} ref={fileRef} type="file" accept=".json" className="sr-only" onChange={e=>restore(e.target.files?.[0])}/></div>
  {error?<div role="alert" className="mt-3 text-rose-200"><DiagnosticText code={error} locale={locale}/></div>:null}
  <p data-testid="case-unassigned-gaps" className="mt-3">{ar?"فجوات تحتاج تعيين مسؤول":"Gaps awaiting an explicit owner"}: {gapRequirements(workspace).length-entries.length}</p>
  <p data-testid="case-actions-count" className="mt-3">{ar?'الإجراءات المفتوحة':'Open actions'}: {entries.filter(e=>e.history.currentStatus!=='CLOSED').length}</p>
  {entries.map(entry=><article key={entry.action.actionId} className="mt-3 rounded border border-slate-700 p-3"><DiagnosticText code={entry.action.description} locale={locale}/><p data-user-content translate="no" className="my-2">{entry.action.ownerId} · {entry.action.dueDate}</p><DiagnosticText code={entry.history.currentStatus} locale={locale}/><div className="mt-3 flex flex-wrap gap-2">{(entry.history.currentStatus===ACTION_STATUS.OPEN?[['IN_PROGRESS',ar?'بدء الإجراء':'Start action']]:entry.history.currentStatus==='IN_PROGRESS'?[['SATISFIED_PENDING_REVIEW',ar?'إحالة الأدلة للمراجعة':'Submit evidence for review']]:entry.history.currentStatus==='SATISFIED_PENDING_REVIEW'?[['CLOSED',ar?'تسجيل الإغلاق البشري':'Record human closure']]:[]).map(([status,label])=><button data-testid={`case-action-${status}`} disabled={busy} key={status} type="button" onClick={()=>advance(entry,status)} className="rounded border border-slate-600 px-3 py-2">{label}</button>)}</div><details className="mt-2"><summary className="cursor-pointer p-2">{ar?'سجل التغييرات':'Change history'}</summary><ol data-user-content translate="no" className="break-words">{entry.history.events.map(e=><li key={e.sequence}>{e.sequence} · {e.toStatus} · {e.actorId} · {e.occurredAt}</li>)}</ol></details></article>)}
 </section>;
}
