import React,{useState} from 'react';
import DiagnosticText from './DiagnosticText.jsx';
const {useLocale}=require('../i18n/LocaleContext');
const {createRentalCalendar,rentalCalendarDisclosure,SOURCE}=require('../app/rental-calendar-disclosure');
const initial={studyStartDate:'',locationScope:'UNKNOWN',leaseCategory:'UNKNOWN',contractReference:'',lastRentReference:'',exceptionReference:''};
export default function RentalCalendarPanel({mode,inputs,result,context,onChange}){
 const {locale}=useLocale(),ar=locale==='ar-SA';const [draft,setDraft]=useState(context||initial),[error,setError]=useState(null);
 const assessment=rentalCalendarDisclosure({mode,inputs,result,context});
 return <details data-testid="rental-calendar" className="mt-3 rounded-xl border border-slate-600 bg-[#101a2d] p-3 text-xs text-slate-200"><summary className="cursor-pointer p-2 font-semibold">{ar?'تواريخ الدراسة ومراجعة نمو الإيجار':'Study dates and rent-growth review'}</summary>
  <p className="my-2 leading-6">{ar?'الضبط يشمل العقود السكنية والتجارية القائمة والجديدة داخل النطاق العمراني للرياض؛ الأجرة الأولى تُتفق عليها، ويحتاج أي نمو لاحق مراجعة. هذا الجدول يبين تداخل السنوات دون افتراض صفر نمو إلى الأبد أو اعتماد السيناريو قانونيًا.':'The rule covers existing and new residential and commercial leases inside Riyadh urban boundaries. First rent is agreed; later growth needs review. This table shows calendar overlap without assuming perpetual zero growth or legally qualifying the scenario.'}</p>
  <a href={SOURCE.url} target="_blank" rel="noreferrer" className="inline-flex min-h-6 items-center underline text-sky-200">{ar?'مصدر الهيئة العامة للعقار — مراجعة 10 أكتوبر 2026':'REGA source — checked 10 October 2026'}</a>
  <div className="mt-3 grid gap-2 sm:grid-cols-2"><label>{ar?'تاريخ بدء الدراسة':'Study start date'}<input data-testid="rental-start-date" type="date" value={draft.studyStartDate} onChange={e=>setDraft({...draft,studyStartDate:e.target.value})} className="mt-1 w-full rounded bg-slate-950 p-2"/></label>
   <label>{ar?'نطاق الموقع — تصريح المستخدم':'Location — user declared'}<select data-testid="rental-location" className="mt-1 w-full rounded bg-slate-950 p-2" value={draft.locationScope} onChange={e=>setDraft({...draft,locationScope:e.target.value})}>{[['UNKNOWN',ar?'لم يُحدد':'Unknown'],['RIYADH_URBAN',ar?'داخل النطاق العمراني للرياض':'Riyadh urban boundary'],['OTHER',ar?'موقع آخر':'Other location']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
   <label>{ar?'نوع الإيجار':'Lease category'}<select data-testid="rental-category" className="mt-1 w-full rounded bg-slate-950 p-2" value={draft.leaseCategory} onChange={e=>setDraft({...draft,leaseCategory:e.target.value})}>{[['UNKNOWN',ar?'لم يُحدد':'Unknown'],['RESIDENTIAL',ar?'سكني':'Residential'],['COMMERCIAL',ar?'تجاري':'Commercial'],['OTHER',ar?'آخر':'Other']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
   {[["contractReference",ar?'مرجع العقد وتاريخه':'Contract and date reference'],["lastRentReference",ar?'مرجع آخر أجرة موثقة أو أول تأجير':'Last recorded rent or first-letting reference'],["exceptionReference",ar?'مرجع اعتراض مقبول — إن وجد':'Accepted objection reference — if any']].map(([key,label])=><label key={key}>{label}<input maxLength="2000" value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} className="mt-1 w-full rounded bg-slate-950 p-2"/></label>)}
  </div><button data-testid="save-rental-calendar" aria-label={ar?'تسجيل السياق وعرض السنوات':'Record context and show periods'} type="button" className="mt-3 rounded border border-sky-600 px-3 py-2" onClick={()=>{try{onChange(createRentalCalendar(draft));setError(null);}catch(e){setError(e.code);}}}>{ar?'تسجيل السياق وعرض السنوات':'Record context and show periods'}</button>
  {error?<p role="alert"><DiagnosticText code={error} locale={locale}/></p>:null}<p data-testid="rental-calendar-status" className="mt-3"><DiagnosticText code={assessment.status} locale={locale}/></p>
  {assessment.periods.length?<div className="mt-3 overflow-x-auto"><table className="w-full text-start"><thead><tr><th scope="col">{ar?'السنة':'Year'}</th><th scope="col">{ar?'الفترة التقويمية':'Calendar period'}</th><th scope="col">{ar?'حالة المراجعة':'Review status'}</th></tr></thead><tbody>{assessment.periods.map(p=><tr key={p.year}><th scope="row" className="p-2">{p.year}</th><td className="p-2" data-user-content translate="no">{p.startDate} → {p.endDateExclusive}</td><td className="p-2"><DiagnosticText code={p.status} locale={locale}/></td></tr>)}</tbody></table></div>:null}
 </details>;
}
