// src/contracts/study-level.js -- canonical StudyLevel contract.
const STUDY_LEVEL = Object.freeze({
  SCREENING: 'SCREENING',
  FULL_UNDERWRITING: 'FULL_UNDERWRITING',
  INVESTMENT_COMMITTEE: 'INVESTMENT_COMMITTEE',
});
const STUDY_LEVEL_STATUS = Object.freeze({
  [STUDY_LEVEL.SCREENING]: 'IMPLEMENTED_CURRENT_BEHAVIOR',
  [STUDY_LEVEL.FULL_UNDERWRITING]: 'PLANNED_NOT_IMPLEMENTED',
  [STUDY_LEVEL.INVESTMENT_COMMITTEE]: 'PLANNED_NOT_IMPLEMENTED',
});
module.exports = { STUDY_LEVEL, STUDY_LEVEL_STATUS };
